# Generated by Django 2.0.5 on 2018-05-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('secs', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=500)),
                ('CDNumber', models.IntegerField(default=-1)),
                ('CDName', models.CharField(max_length=500)),
                ('tracknum', models.IntegerField(default=0)),
            ],
        ),
    ]
